import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin-ext'],

})

export const metadata = {
  title: 'Kepoin Paket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
